### ISSUE TITLE
NoSuchMethodError somewhere in Beagle.initialize() after moving to Hilt

### ISSUE THREAD

**Issue by howelltw** [pandulapeter/beagle#100]
My Beagle initialize code was working before, but now gets this error after adding some basic Hilt DI code in the app (non of which "provides" or does anything with Beagle).

java.lang.NoSuchMethodError: No virtual method add(Lcoil/fetch/Fetcher;Ljava/lang/Class;)Lcoil/ComponentRegistry$Builder; in class Lcoil/ComponentRegistry$Builder; or its super classes (declaration of 'coil.ComponentRegistry$Builder' appears in /data/app/~~8D1EvffnxWVvXAR3q2LLkA==/com.example.netgear-1_TE_2vSFnaeaJqOD09h7w==/base.apk)
                                                                                                    	at com.pandulapeter.beagle.core.BeagleImplementation.initialize(BeagleImplementation.kt:492)
                                                                                                    	at com.pandulapeter.beagle.Beagle.initialize(Unknown Source:17)
                                                                                                    	at com.pandulapeter.beagle.common.contracts.BeagleContract.initialize$default(BeagleContract.kt:59)
                                                                                                    	at com.example.netgear.NetgearApplication.onCreate(NetgearApplication.kt:16)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7482)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2283)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8641)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

I have pretty generic Beagle initialize code, pretty much straight from the example code, but I can post it if it helps any.

**Comment by pandulapeter** [comment]
Hi!

This is probably caused by incompatible Coil versions. Beagle contains the latest stable version (1.4.0) and your app probably overrides this with one of the 2.0.0 artifacts, where the API changed and they removed some classes.

Unfortunately Coil 2.0.0 is still in RC and I only include stable versions. So until Coil 2.0.0 is final, I suggest you downgrade to Coil 1.4.0, that should fix the issue.

**Comment by jakoss** [comment]
The RC version is very stable and it moving very slow. How about releasing beagle-rc version with rc dependency? We want to use new coil and we have to disable beagle to do that which is unfortunate

**Comment by pandulapeter** [comment]
Let's keep it simple, you're right that release candidates should be stable enough. Release [2.7.1](https://github.com/pandulapeter/beagle/releases/tag/2.7.1) now has the latest RC version of Coil. For the sake of consistency, it also contains the latest RC version of Material. This should fix the issue.

**Comment by howelltw** [comment]
Thanks! 2.7.1 fixes the issue for me.
