### ISSUE TITLE
TextInputModule Crash 

### ISSUE THREAD

**Issue by nazarabd3005** [pandulapeter/beagle#102]
I trying to add Module 
`  TextInputModule("halo", initialValue = "Input Transaction ID here", shouldRequireConfirmation = false, onValueChanged = { }),`

when **shouldRequireConfirmation** change to **true** I getting the crash:
here is the log:
`android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7313)
        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1161)
        at android.view.View.requestLayout(View.java:21995)
        at android.view.View.requestLayout(View.java:21995)
        at android.view.View.requestLayout(View.java:21995)
        at android.view.View.requestLayout(View.java:21995)
        at android.view.View.requestLayout(View.java:21995)
        at android.view.View.requestLayout(View.java:21995)
        at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
        at android.view.View.requestLayout(View.java:21995)
        at android.view.View.requestLayout(View.java:21995)
        at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
        at android.view.View.internalSetPadding(View.java:21006)
        at android.view.ViewGroup.internalSetPadding(ViewGroup.java:3709)
        at android.view.View.setPadding(View.java:20947)
        at com.pandulapeter.beagle.core.view.InternalDebugMenuView.updatePadding(InternalDebugMenuView.kt:141)
        at com.pandulapeter.beagle.core.view.InternalDebugMenuView.onContentsChanged(InternalDebugMenuView.kt:105)
        at com.pandulapeter.beagle.core.manager.listener.UpdateListenerManager$notifyListenersOnContentsChanged$1.invoke(UpdateListenerManager.kt:7)
        at com.pandulapeter.beagle.core.manager.listener.UpdateListenerManager$notifyListenersOnContentsChanged$1.invoke(UpdateListenerManager.kt:7)
        at com.pandulapeter.beagle.core.manager.listener.BaseListenerManager.notifyListeners(BaseListenerManager.kt:64)
        at com.pandulapeter.beagle.core.manager.listener.UpdateListenerManager.notifyListenersOnContentsChanged(UpdateListenerManager.kt:7)
        at com.pandulapeter.beagle.core.BeagleImplementation$refresh$1.invoke(BeagleImplementation.kt:322)
        at com.pandulapeter.beagle.core.BeagleImplementation$refresh$1.invoke(BeagleImplementation.kt:322)
        at com.pandulapeter.beagle.core.manager.ListManager$refreshCellsInternal$2$1.invoke(ListManager.kt:267)
        at com.pandulapeter.beagle.core.manager.ListManager$refreshCellsInternal$2$1.invoke(ListManager.kt:266)
        at com.pandulapeter.beagle.core.list.CellAdapter.processQueue(CellAdapter.kt:69)
        at com.pandulapeter.beagle.core.list.CellAdapter.access$processQueue(CellAdapter.kt:16)
        at com.pandulapeter.beagle.core.list.CellAdapter$update$1$1$1.invokeSuspend(CellAdapter.kt:59)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
         MainActivity has leaked window DecorView@818b2f2[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:330)
        at com.pandulapeter.beagle.core.list.delegates.TextInputDelegate$createCells$2$1.invoke(TextInputDelegate.kt:46)
        at com.pandulapeter.beagle.core.list.delegates.TextInputDelegate$createCells$2$1.invoke(TextInputDelegate.kt:28)
        at com.pandulapeter.beagle.core.list.cells.TextCell$TextViewHolder.bind$lambda-3$lambda-2$lambda-1(TextCell.kt:54)
        at com.pandulapeter.beagle.core.list.cells.TextCell$TextViewHolder.$r8$lambda$0PflZ2sNu2ByAQSFUWoSyIU_IF0(Unknown Source:0)
        at com.pandulapeter.beagle.core.list.cells.TextCell$TextViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by pandulapeter** [comment]
Whoa, sorry, that was an ugly one. I managed to reproduce the issue, and it should be fixed in the latest [v2.8.0 release](https://github.com/pandulapeter/beagle/releases/tag/2.8.0).

Keep in mind that starting with this version, Beagle is hosted on MavenCentral and the artifact ID for it should be changed from `com.github.pandulapeter.beagle....` to `io.github.pandulapeter.beagle...`.

Thanks for reporting the issue!

**Comment by nazarabd3005** [comment]
@pandulapeter Thanks2
