### ISSUE TITLE
[Bug] NetworkLogManager crashing application with concurrent modification exception 

### ISSUE THREAD

**Issue by fknives** [pandulapeter/beagle#32]
**Description**
I noticed a crash in my application which seems to be originating from Beagle.
The issue seems to be in the NetworkLogManager, in my case the problem was occurring by the sort function. In line 24 there is a `entries.sortByDescending { it.timestamp }`.

**Repro steps**
By the nature of the exception (ConcurrentModificationException) I cannot provide a good repro steps.

**Version**
the used version is 2.0.0-beta01
Based on the fact that this class has not been modified between beta01 and beta06 I assume the issue would still persist

**Suggestion to fix**
I suggest to use immutable list in the NetworkLogManager.entries so there is no possibility for concurrent modification.
Other possible solution could be to use other synchronization mechanizm

**Stracktrace**
`java.util.ConcurrentModificationException
        at java.util.ArrayList.sort(ArrayList.java:1472)
        at java.util.Collections.sort(Collections.java:206)
        at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
        at com.pandulapeter.beagle.core.manager.NetworkLogManager.log(NetworkLogManager.kt:40)
        at com.pandulapeter.beagle.core.BeagleImplementation.logNetworkEvent(BeagleImplementation.kt:150)
        at com.pandulapeter.beagle.common.contracts.BeagleContract$DefaultImpls.logNetworkEvent$default(BeagleContract.kt:301)
        at com.pandulapeter.beagle.core.util.NetworkInterceptor.intercept(NetworkInterceptor.kt:63)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at ***.OkHttpClientProvider$provide$1.intercept(OkHttpClientProvider.kt:29)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by fknives** [comment]
@pandulapeter I have a solution with synchronization to this so I could make a pull request if you grant permission for me.

**Comment by pandulapeter** [comment]
Thanks a lot, that would be very helpful! I'm not in front of my computer today but tomorrow I'll sort out the permission stuff.

**Comment by pandulapeter** [comment]
I did leave some TODO-s about the possibility of this exception (maybe in the ListManager class), is that where your fix would be?

**Comment by fknives** [comment]
It is in the NetworkLogManager since that's where the issue originated for me and the list modifications happen.

**Comment by pandulapeter** [comment]
Awesome, thanks a lot! Let me add your solution to a couple other places where it might be needed and do some testing - I'll close this issue when the new version is released.

**Comment by pandulapeter** [comment]
The fixes are part of v2.0.0-beta07
