### ISSUE TITLE
Coil upgrade to 1.0.0.rc1

### ISSUE THREAD

**Issue by jakoss** [pandulapeter/beagle#36]
RC release of coil broke backwards compatibility and after upgrading it in my project - beagle is crashing on initialize. Could you release version with bumped coil version?

Version 0.12.0 does not work too

**Comment by pandulapeter** [comment]
I'm having some problems upgrading to Kotlin 1.4 so this might take a while (the new version of Coil seems to require it). I'm looking into this right now, but can't you [exclude Coil from Beagle](https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991) somehow? I was unable to reproduce the crash you mentioned, do you have some logs? Is it a NoClassDefFoundError?

**Comment by jakoss** [comment]
I'm not in a rush, 0.11.0 works for me just fine. If you have issues with Kotlin 1.4 you can try with Coil 0.12.0 which have the same api but it's targeting kotlin 1.3

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcoil/ImageLoaderBuilder;
        at com.pandulapeter.beagle.core.BeagleImplementation.initialize(BeagleImplementation.kt:205)
        at com.pandulapeter.beagle.Beagle.initialize(Unknown Source:17)
        at com.pandulapeter.beagle.common.contracts.BeagleContract$DefaultImpls.initialize$default(BeagleContract.kt:51)
        at com.asd.android.DebugApplication.onCreate(DebugApplication.kt:43)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "coil.ImageLoaderBuilder" on path: DexPathList[[zip file "/data/app/com.asd.android.dev-prGZ8Ve1ZOFAPjJu7MRY7g==/base.apk"],nativeLibraryDirectories=[/data/app/com.asd.android.dev-prGZ8Ve1ZOFAPjJu7MRY7g==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.pandulapeter.beagle.core.BeagleImplementation.initialize(BeagleImplementation.kt:205) 
        at com.pandulapeter.beagle.Beagle.initialize(Unknown Source:17) 
        at com.pandulapeter.beagle.common.contracts.BeagleContract$DefaultImpls.initialize$default(BeagleContract.kt:51) 
        at com.asd.android.DebugApplication.onCreate(DebugApplication.kt:43) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by pandulapeter** [comment]
I think we're good now. There is a new release ([2.0.0-beta15](https://github.com/pandulapeter/beagle/releases/tag/2.0.0-beta15)) which uses Kotlin 1.4 and Coin 1.0.0-rc1. Thanks for raising the issue, let me know if you run into any other problems!

**Comment by jakoss** [comment]
I run into a problem with implementing VisibilityListener:

![image](https://user-images.githubusercontent.com/3933348/90625424-d727f000-e219-11ea-8b12-023299f26e55.png)

**Comment by pandulapeter** [comment]
I had the same issue with the example app... Looks like all clients have to do it, I'll add it to the readme then.

Adding this to the end of the module-level build.gradle file should fix it:

`tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
        freeCompilerArgs = ["-Xjvm-default=all"]
    }
}`

**Comment by jakoss** [comment]
That helped, thanks
