### ISSUE TITLE
ViewBoundsOverlayToggle crash

### ISSUE THREAD

**Issue by egorikftp** [pandulapeter/beagle#5]
Hi. Thanks for the nice library. I found the crash for some functionality such as **ViewBoundsOverlayToggle**

If I enable this functionality, that crash happens. Looks like the problem in **OverlayFrameLayout**.  Should be  `GlobalScope.launch(Dispatchers.Main) {}`

Crash log:

` android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6855)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1075)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5242)
        at android.view.View.invalidateInternal(View.java:13574)
        at android.view.View.invalidate(View.java:13538)
        at android.view.View.invalidate(View.java:13522)
        at com.pandulapeter.beagle.views.OverlayFrameLayout$startAutomaticRefresh$1.invokeSuspend(OverlayFrameLayout.kt:71)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)`

**Comment by pandulapeter** [comment]
Thanks a lot for reporting this issue! I wasn't able to reproduce it but it's pretty clear from your logs, so I've implemented switching back to the main thread before invalidating the View hierarchy - it should not happen anymore. The fix is part of version v1.3.2 - let me know if you have any other issues.
