### ISSUE TITLE
DrawerLayout throws IllegalArgumentException on system permission dialog

### ISSUE THREAD

**Issue by pawegio** [pandulapeter/beagle#57]
I picked **ui-drawer** implementation that works fine until following exception is thrown when Beagle is initialized and system permission dialog is requested:

```
Fatal Exception: java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.
       at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1053)
       at android.view.View.measure(View.java:26411)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at android.view.View.measure(View.java:26411)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
       at android.view.View.measure(View.java:26411)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7845)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1050)
       at android.view.View.measure(View.java:26411)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3638)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2346)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2665)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
       at android.view.Choreographer.doCallbacks(Choreographer.java:797)
       at android.view.Choreographer.doFrame(Choreographer.java:732)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

For now, I switched to **ui-bottom-sheet** implementation that has no issues. However, drawer was just nicer for debug menu. :)

I'm using latest `2.0.2` version and initialization is invoked in `Application.onCreate()` method.

**Comment by pandulapeter** [comment]
Hi!

Sorry to hear about that, but I'm glad the **ui-bottom-sheet** workaround works for the time being.

If the crash happens the moment you bring up the system permission dialog, this probably means that Beagle is trying to inject itself into the transparent Activity coming from the system. I was confident that I handled this case and since I cannot reproduce it, it might be device / OS specific. Could you please add a [LifecycleLogListModule](https://github.com/pandulapeter/beagle/blob/master/common/src/main/java/com/pandulapeter/beagle/modules/LifecycleLogListModule.kt) to your debug bottom sheet or use the debugger to find out what the full name of that system Activity is? Then you could manually exclude that package name and get back to using the drawer:

```
Beagle.initialize(
    application = this,
    behavior = Behavior(
        ...
        excludedPackageNames = listOf("excluded.package.name.here")
    )
)
```
Let me know if you find out more information and also please post the device OS version so that I can come up with a nicer solution for the next release.

**Comment by pawegio** [comment]
Thank you for support! Indeed the reason was inappropriate activity launched by third-party [Peko library](https://github.com/deva666/Peko). I forgot to mention this.

The exclusion below resolved this:
```
Beagle.initialize(
    application = this,
    behavior = Behavior(excludedPackageNames = listOf("com.markodevcic.peko.PekoActivity"))
)
```

Device: Pixel 3 with Android 11

**Comment by pandulapeter** [comment]
Awesome, thanks for the update! I wasn't familiar with this library (I suspected some custom Android skin using some weird permission handling Activity). In the next release I'll add the package name you sent to the internal list of excluded package names so you'll be able to remove that line.
