### ISSUE TITLE
UncaughtExceptionHandler does not work in minfied builds.

### ISSUE THREAD

**Issue by pandulapeter** [pandulapeter/beagle#63]
The Service can't seem to start the BugReportActivity when minifyEnabled = true. The feature works fine in builds where minification is turned off. Not sure what's the difference, ProGuard rules can't seem to circumvent it. Relevant classes:
- [ExceptionHandler](https://github.com/pandulapeter/beagle/blob/master/core/src/main/java/com/pandulapeter/beagle/core/manager/ExceptionHandler.kt)
- [ExceptionHandlerService](https://github.com/pandulapeter/beagle/blob/master/core/src/main/java/com/pandulapeter/beagle/core/util/ExceptionHandlerService.kt)
- [AndroidManifest](https://github.com/pandulapeter/beagle/blob/master/core/src/main/AndroidManifest.xml)

The following exception is thrown:
```
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:575)
        ...
```

This should only happen if the activity was started by the process we just killed. This should not be the case as the Service is bound to a separate process. Minification changes the behavior somehow.

**Comment by pandulapeter** [comment]
Fixed in [release 2.3.2](https://github.com/pandulapeter/beagle/releases/tag/2.3.2). Turns out it was a problem with passing the data between the Service and the Activity, but the exception itself was not displayed due to the very nature of this feature.
