### ISSUE TITLE
OutOfMemory issues 

### ISSUE THREAD

**Issue by tamashalcyon** [pandulapeter/beagle#91]
OutOfMemory issues on lower-end devices when trying to call the log() method of the LogManager, NetworkLogManager, LifecycleLogManager. 
See logs from Firebase Crashlytics:
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 2434992 free bytes and 2377KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 8650752 bytes)
       at java.lang.Long.valueOf(Long.java:845)
       at com.pandulapeter.beagle.core.manager.LogManager$log$lambda-1$$inlined$sortByDescending$1.compare(LogManager.java:2)
       at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
       at java.util.TimSort.sort(TimSort.java:234)
       at java.util.Arrays.sort(Arrays.java:1492)
       at java.util.ArrayList.sort(ArrayList.java:1470)
       at java.util.Collections.sort(Collections.java:206)
       at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(CollectionsKt__MutableCollectionsJVMKt.java:17)
       at com.pandulapeter.beagle.core.manager.LogManager.log(LogManager.java:18)
       at com.pandulapeter.beagle.core.BeagleImplementation.log(BeagleImplementation.java:18)
       at com.pandulapeter.beagle.core.BeagleImplementation.log(BeagleImplementation.java:18)
       at com.pandulapeter.beagle.core.BeagleImplementation.access$log(BeagleImplementation.java:18)
       at com.pandulapeter.beagle.core.BeagleImplementation$initialize$1$2$1.invoke(BeagleImplementation.java:18)
       at com.pandulapeter.beagle.core.BeagleImplementation$initialize$1$2$1.invoke(BeagleImplementation.java:18)
       at com.pandulapeter.beagle.log.LoggerImplementation.log(LoggerImplementation.java:33)
       at com.pandulapeter.beagle.log.BeagleLogger.log(BeagleLogger.java:20)
       at com.pandulapeter.beagle.commonBase.BeagleLoggerContract$DefaultImpls.log$default(BeagleLoggerContract.java:2)
       at com.urbantz.mobile.UrbantzApp$BeagleLogTree.log(UrbantzApp.java:2)
       at timber.log.Timber$Tree.prepareLog(Timber.java:4)
       at timber.log.Timber$Tree.d(Timber.java:2)
       at timber.log.Timber$1.d(Timber.java:8)
       at timber.log.Timber.d(Timber.java:10)
       at com.urbantz.mobile.feature.rounds.preparation.RoundPreparationSharedViewModel.handleStoreResponse(RoundPreparationSharedViewModel.java:10)
       at com.urbantz.mobile.feature.rounds.preparation.RoundPreparationSharedViewModel.access$handleStoreResponse(RoundPreparationSharedViewModel.java:10)
       at com.urbantz.mobile.feature.rounds.preparation.RoundPreparationSharedViewModel$round$1.invokeSuspend(RoundPreparationSharedViewModel.java:10)
       at com.urbantz.mobile.feature.rounds.preparation.RoundPreparationSharedViewModel$round$1.invoke(RoundPreparationSharedViewModel.java:10)
       at com.urbantz.mobile.feature.rounds.preparation.RoundPreparationSharedViewModel$round$1.invoke(RoundPreparationSharedViewModel.java:10)
       at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(FlowKt__TransformKt.java:73)
       at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(FlowKt__TransformKt.java:89)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:1)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:15)
       at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineSuspended(DebugProbesKt.java)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:1)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:15)
       at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineSuspended(DebugProbesKt.java)
       at com.dropbox.android.external.store4.impl.RealStore$stream$1$invokeSuspend$$inlined$transform$1$1.a(RealStore.java:83)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:1)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:15)
       at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineSuspended(DebugProbesKt.java)
       at com.dropbox.android.external.store4.impl.RealStore$diskNetworkCombined$$inlined$transform$1$1.emit(RealStore.java:12)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(FlowKt__ChannelsKt.java:8)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl(FlowKt__ChannelsKt.java:1)
       at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(FlowKt__ChannelsKt.java:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:2)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:86)
       at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.java:2)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTaskKt.java:3)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.java:3)
       at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.java:2)
       at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.java:4)
       at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.java:2)
       at kotlinx.coroutines.channels.AbstractSendChannel.sendSuspend(AbstractSendChannel.java)
       at kotlinx.coroutines.channels.ChannelCoroutine.send(ChannelCoroutine.java:2)
       at kotlinx.coroutines.flow.internal.SendingCollector.emit(SendingCollector.java:2)
       at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catchImpl$$inlined$collect$1.emit(FlowKt__ErrorsKt.java:62)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:1)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:15)
       at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineSuspended(DebugProbesKt.java)
       at com.dropbox.android.external.store4.impl.SourceOfTruthWithBarrier$reader$1$invokeSuspend$lambda-1$$inlined$mapIndexed$1$1.emit(SourceOfTruthWithBarrier.java:2)
       at com.urbantz.storage.repository.round.RoundLocalSourceImpl$getFlow$$inlined$map$1$2.emit(RoundLocalSourceImpl.java:2)
       at kotlinx.coroutines.flow.DistinctFlowImpl$collect$$inlined$collect$1.emit(DistinctFlowImpl.java:90)
       at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollectorKt.java:1)
       at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.java:15)
       at kotlin.coroutines.jvm.internal.DebugProbesKt.probeCoroutineSuspended(DebugProbesKt.java)
       at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.java:34)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:2)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:86)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

I'm not sure if it would solve the problem but I would say you can give it a try to use the `sortByDescending` on a Sequence instead of the Collection. (using asSequcen())

**Comment by pandulapeter** [comment]
@tamashalcyon I interoduced a new API in version 2.6.5 which allows you to limit the maximum number of log entries. Unfrotunately Beagle was designed in a way to keep everything in memory, which is finite :( However, playing around with this value should help avoid the crash.

[This commit](https://github.com/pandulapeter/beagle/commit/9ba17802a2df9542a97a2da64210073ed9f42d54) contains the changes.
