### ISSUE TITLE
StrictMode WrongFragmentContainerViolation

### ISSUE THREAD

**Issue by DanielNovak** [pandulapeter/beagle#94]
Enabling Fragment strict mode reports an issue from within Beagle. We are using the `ui-drawer` plugin. I haven't looked deeper into the Beable source code yet. It seems that Beagle is adding the OverlayFragment into a `ContentFrameLayout` but Fragments should always be placed into a `FragmentContainerView` (this fixes som z-ordering and animation issues). I guess it's not a big issue since Beagle is meant for debug builds and it doesn't matter - but on the other hand this log is creating noise...

```
D/FragmentStrictMode: Policy violation in com.pandulapeter.beagle.core.OverlayFragment
    androidx.fragment.app.strictmode.WrongFragmentContainerViolation: Attempting to add fragment OverlayFragment{1f0df8e} (449ada5e-dd11-4cac-9637-a72e9c8a39e2 id=0x1020002) to container androidx.appcompat.widget.ContentFrameLayout{3bb9fda V.E...... ......ID 0,0-1080,2160 #1020002 android:id/content} which is not a FragmentContainerView
        at androidx.fragment.app.strictmode.FragmentStrictMode.onWrongFragmentContainer(FragmentStrictMode.kt:204)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by pandulapeter** [comment]
Hi!

The warning is valid, OverlayFragment is the main container for Beagle and it's above the rest of the app no matter which artifact you're using (except for `noop` of course). It's not only needed for the drawer, but for other features as well, such as drawing the keyline overlay.

The problem is that the only way I found to add a Fragment into any project is to use `android.R.id.content` which is the root ViewGroup for the Activity. That's what OverlayFragment is added too, and it happens to be a ContentFrameLayout.

There will be improvements made to this to fix [this bug](https://github.com/pandulapeter/beagle/issues/93), but I don't think that the core idea will change.

I'm sorry about the log spam but at this point I suggest you ignore the warnings. As you said, it won't be an issue for release builds, and even for debug builds the z-ordering / transitioning problems don't apply (as OverlayFragment will always stay there and it's a layer above the rest of your Fragments).
